### ISSUE TITLE
Stage 1 should not rebuild the entire data inventory on every run

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#1]
Stage 1 currently obtains a list of all images under /data before it builds the data inventory. This is inefficient given that several images may have already been processed in previous runs and do not need to be reprocessed. Stage 1 should therefore check for pre-existing reductions and identify only new images where it is necessary to perform the analysis.

**Comment by ytsapras** [comment]
I have tried using the function find_images_need_to_be_process from stage0 to check for new images but the output is a path instead of a list. We need to coordinate with Etienne to fix this.

(I think it is preferable if all functions that query or interact with the metadata are in metadata.py and not in stage0.)

What is needed:

The function should check the metadata layer to obtain a list of all images already processed by stage 1, then check for new images for stage 1 to process.
If none are found, an empty list is returned. If one or more are found, a list with the image names is returned.
Stage 1 goes through every image, evaluates the parameters and fills the relevant section in the metadata.

**Comment by ytsapras** [comment]
We need a function to return a list of the images that need to be processed for a specific stage.
For example, when I run stage 1, I only want to run it on the images that stage 1 has not already been run on. (add a boolean 'redo_all' option).

e.g. call:
```
from reduction_control import *
setup = get_args()
#(give the path to the reduction directory at the prompt)
# you should then get a response such as: setup.red_dir = '/.../pyDANDIA/pyDANDIA/tests/data/proc/ROME-FIELD-0002_lsc-doma-1m0-05-fl15_ip'

reduction_metadata = metadata.MetaData()
images = reduction_metadata.find_images_to_process(setup,
				 reduction_metadata=reduction_metadata,
				 list_of_images=setup.red_dir,
                                 stage='stage1'
				 log=None)
```

**Comment by ebachelet** [comment]
You should be able to use metadata.find_images_need_to_be_process, have a look on run_stage0

**Comment by ytsapras** [comment]
Stage1 now works with the new metadata. Note that when stage0 is run again, it resets the REDUCTION_STATUS column for stage1 to 0 again, even though stage1 has already set it to 1.

**Comment by ebachelet** [comment]
Fixed.
