### ISSUE TITLE
stage0 calculation of stamp size only works for square arrays of stamps

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#106]
Stage 0 is failing to calculate the correct dimensions for the stamps at line 670:

stamps_x_max[:,-1] = [image.shape[1]]*len(stamps_x_max[-1,:])

where it crashes with an error complaining that the calculated list of entries (length 2 in my test case) does not fit into the stamps_x_max[:,-1] array (length 4 in test).  This is occurring because the images in my test case are not symmetrically symmetric but rather are full width in x and ~half the full frame in y.  

I believe this line should be:

stamps_x_max[-1,:] = [image.shape[1]]*len(stamps_x_max[-1,:])

...which would make it similar to the corresponding y-direction calculation. 

I think this bug has not affected the DR1 reductions because the stamp array used happens to be symmetrical for the full frame images.  I'm filling this issue for the team's information and record, and I will fix it in branch crop_frame_reductions.

**Comment by rachel3834** [comment]
I'd appreciate it if whoever wrote this stage could take a look.

**Comment by ebachelet** [comment]
I just push an update which should fix this issue. This was due to an double minor bugs, unoticed if the array are square.

**Comment by rachel3834** [comment]
Test with the MB190284 data demonstrates the fixed code appears to be working as expected now.  Thanks Etienne.
