### ISSUE TITLE
Stage 5 umatrix binary incompatibility

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#111]
Running the pipeline on my Macbook, I get the following error for stage 5:

  File "/Users/rstreet1/software/pydandia_venv/lib/python3.7/site-packages/pyDANDIA-0.1-py3.7-macosx-10.14-x86_64.egg/pyDANDIA/stage5.py", line 55, in run_stage5
    from umatrix_routine import umatrix_construction, umatrix_bvector_construction, bvector_construction
  File "__init__.pxd", line 918, in init umatrix_routine
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Has anyone else seen this?  It could be an issue with the OS, but recompiling has not resolved it.

**Comment by ebachelet** [comment]
Which numpy version do you use? It might be similar to:
https://github.com/scikit-learn-contrib/hdbscan/issues/272

**Comment by rachel3834** [comment]
1.14.5.  Interesting, it does sound related.  Yet strangely the ROME reductions used 1.14.5 without an issue.

**Comment by rachel3834** [comment]
Looks like upgrading numpy to 1.16.0 does solve this issue under MacOS
