### ISSUE TITLE
build umatrix code

### ISSUE THREAD

**Issue by mpgh** [pyDANDIA/pyDANDIA#16]
Since I was asked how to compile the umatrix code, I just want to ask if the following steps are too involved:
 http://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html
That requires to use a setup.py file and build the module as follows:
python setup.py build_ext --inplace

**Comment by ebachelet** [comment]
That should be fine, if this is only once?

**Comment by mpgh** [comment]
It requires only one setup call and the module can be imported thereafter.

**Comment by mpgh** [comment]
By adding the np.get_include path and checking for ImportErrors we should be fine.
