### ISSUE TITLE
stage3 - subdirectory for products

### ISSUE THREAD

**Issue by mpgh** [pyDANDIA/pyDANDIA#17]
wcs, res and starcatalog fits files deserve their own directory because they are mistaken for images when re-running the pipeline.

**Comment by ebachelet** [comment]
First, star catalogs is in the metadata if I correctly understand stage3 (correct@rstreet?). So any of these files should be deleted.

Moreover, the metadata contains an output_directory path. So any stages how produces outputs should use this to save its products (and eventually create a subdirectory)

**Comment by rachel3834** [comment]
Yes the star catalog is a layer in the metadata.

**Comment by ebachelet** [comment]
OK so should we keep a separate star_catalog.fits then? It looks stage3 still produce it.

Also, stage3 produce a _ref.fits and a _wcs.fits, that are stored in the image data, creating issue for new pipeline runs. Could we store it somewhere else? Are they useful?

**Comment by rachel3834** [comment]
That can be switched off - its a debugging output

The _ref and _wcs should be output to the reference image directory.  I didn't think that this would cause a problem?  I think they are useful to keep, certainly at least for the time being until we know how the pipeline behaves for different datasets.

**Comment by ebachelet** [comment]
I also agree they useful, it is just at the time been they are outputed on the wrong directory, raw_images ones.

**Comment by rachel3834** [comment]
Ah OK, redirecting that output should be an easy fix.

**Comment by rachel3834** [comment]
Ah, so looking into this problem, this is residual code that I put in early on before we'd settled on the directory structure.  

It can be redirected easily so it picks up the reference image from the ref/ subdirectory, provided we have settled on where stage3 can get the path to the reference image from (somewhere in the metadata).  If that has been decided, please let me know how to read that parameter from the metadata and I will update this stage.

**Comment by ebachelet** [comment]
Great!

So the path for the ref directory and image name are on the data_architecture layer with keys : 
REF_PATH
REF_IMAGE

**Comment by rachel3834** [comment]
I've implemented a fix and merged the branch with master.  However, I can't test the code because the metadata file currently in the pyDANDIA/pyDANDIA/tests/data/proc/ROME-FIELD-0002_lsc-doma-1m0-05-fl15_ip test dataset doesn't have the REF_PATH and REF_IMAGE parameters in it.  

Please can you  commit an up-to-date version of the metadata file for the test dataset?

I'll leave this issue open until its fully tested.

**Comment by ebachelet** [comment]
Good. You can produce the correct metadata by running all stages from starting from stage 0 if you want to test. Should be pretty quick.

**Comment by ebachelet** [comment]
Fixed.
