### ISSUE TITLE
stage2 fail when rerunning reduction

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#24]
I guess this is due to this lane :

if not 'REF_PATH' in str(reduction_metadata.data_architecture[1]) and  not 'REF_IMAGE' in str(reduction_metadata.data_architecture[1]):
           
The condition looks strange. Also, what happen if we change the reference? This nees to be improved.

**Comment by mpgh** [comment]
okay, it should have accessed the keys instead of the output. Fixed.
