### ISSUE TITLE
stage2 and stage3 does not update image status in the metadata

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#25]
I think we need to add these lines to the stages : 

    # Update the REDUCTION_STATUS table in metadata for stage 1

    reduction_metadata.update_reduction_metadata_reduction_status(images,
                                                                  stage_number=1, status=1, log=log)

**Comment by mpgh** [comment]
I have tried to fix that on stage2 but running the stage crashes:                                     
IndexError: 'index 0 is out of bounds for axis 0 with size 0'
That comes from the metadata module when trying to set the status of all images to 1:

reduction_metadata.update_reduction_metadata_reduction_status(all_images,
                                                              stage_number=2, status=1, log=log)

As a side remark, the status is actually 1 afterwards, so it might be one of the last operations of the aforementioned method.

**Comment by ebachelet** [comment]
Fixed.
