### ISSUE TITLE
Problem with the function convert_flux_to_mag() in photometry.py

### ISSUE THREAD

**Issue by danlegend5** [pyDANDIA/pyDANDIA#27]
I see two problems with this function:

(i) It will crash if flux_err > flux because of the calculation of m2.

(ii) The variance propagation formula (first order approximation) is:

m_err = (2.5/ln(10.0))*flux_err/flux

Would this not be better than simply calculating (m2 - m1) / 2.0 ?

**Comment by rachel3834** [comment]
For the life of me, I can't remember why I didn't just use the correct formula, especially since it was in the original fortran routine that I translated!

Anyway, its fixed now.
