### ISSUE TITLE
Verify that metadata.py offers functions to read specific sections of the metadata

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#3]
Stages 1-end will need to read the metadata, so its appropriate that the read/load functions should be in the metadata.py file.

The whole purpose of the metadata architecture was to make the read efficient, so that the stage only needs to read that section of the metadata that it actually needs.

Someone needs to check that metadata offers this functionality, and returns sensible output in the event that a stage tries to read a layer in a metadata file that has not yet been created. For example, the read function could return a status parameter as well as the content.

**Comment by ebachelet** [comment]
There is actually, have a alook to load_a_layer_from_file, or load all_metadata in metadata.py.

Each stage should create a metadata object, then load the needed layers for its purpose, then save them back to file when finished

**Comment by ytsapras** [comment]
Examples of how to do this can be found in stage0 and stage1. Closing this issue.
