### ISSUE TITLE
Nomenculture for stars in reference catalogue

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#37]
The agreed convention for naming stars detected in ROME fields is:
        RRFF_RA_DEC
    
    where RR = ROME/REA
          FF = Two-digit ROME field ID
          RA, DEC = star coordinates in decimal degrees

**Comment by rachel3834** [comment]
I've implemented this convention on a branch of the pipeline but I'm having trouble accessing the field ID for a given dataset.  I don't see it in the metadata anywhere.  The only place I can find it is in the name of the data directory, which isn't ideal.  Any ideas?  We should probably add the field ID to the metadata, maybe under reduction_parameters.  It could be harvested from the image FITS headers, based on the object ID.  

Also: giving the stars ROME-specific naming convention does make the pipeline specific to ROME data rather than general purpose.   But I can make the field ID optional, so if it is not provided the function reverts to a simple numerical index.

**Comment by ytsapras** [comment]
Following our discussion yesterday, this is now obsolete information. We should just use a numbered list that is easier to order and search.

**Comment by rachel3834** [comment]
Agreed.
