### ISSUE TITLE
Software to combine star catalogues

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#38]
Write a code to walk over a set of reduced datasets for several fields and filters and produce a combined star catalogue, cross-matching stars in the process.

**Comment by rachel3834** [comment]
Under development on branch make_uber_catalog

**Comment by ebachelet** [comment]
Hi

Is it really should be include in the pipeline? Sounds like a ROME/REA needs instead

**Comment by rachel3834** [comment]
It makes sense for it to be included in this repo as an added tool because it depends on many of the modules of the pipeline e.g. for reading the metadata etc.

**Comment by ytsapras** [comment]
It might be worth creating another directory in the repo (/external/) that can be used for project specific code.

So pyDANDIA only does the photometry for a given set of images and a fixed star catalog and anything extra people want to do with it can be added in that directory.

**Comment by rachel3834** [comment]
Yes that would make sense.  Will do.

**Comment by rachel3834** [comment]
First version of this software is complete and merged with the master.  More complete testing will require more than one completed field reduction.

**Comment by ytsapras** [comment]
This seems to be complete now. Closing.
