### ISSUE TITLE
Constructing pixel masks in Stage 0

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#5]
When I run stage 0 on the test dataset, all images seem to trigger the try...except clause and no mask is made. Investigation is needed to figure out why this is happening and fix the bug.

**Comment by ebachelet** [comment]
This should be corrected. This come from a mismatch on the bpm size and image size in  the test data. A mission for @mpgh

**Comment by mpgh** [comment]
The original mask comes from a fullframe Sinistro. The test dataset was cropped but I haven't cropped the extra extension that contains the bpm. One "solution" would be to replace the subframes with full Sinistro frames....

**Comment by mpgh** [comment]
It is not perfectly clear to me which of the 2 extra masks that are stored in the extensions of LCO data belongs to the bpm. The first extension after the data should be the photometry. The next 2 could both be bpms. As a pragmatic solution, I would suggest to set them 0 for our test dataset and expect to start stage0 with a full frame and the right bpm index (tbd).
