### ISSUE TITLE
increase metadata columns for stage5 at stage0

### ISSUE THREAD

**Issue by mpgh** [pyDANDIA/pyDANDIA#57]
We need to make sure that the image background is not calculated multiple times for each image but determined once for every subimage. For that purpose, I would like to suggest to add 5 columns to the corresponding table that can be populated by stage5. For every subimage we need: 3 parameters (background gradient), scale factor and additional background from difference imaging.

**Comment by rachel3834** [comment]
This sounds like a good idea, which table should they be added to?

**Comment by mpgh** [comment]
I would suggest to use the table that contains the subimage slices and extend it, i.e.
reduction_metadata.stamps

**Comment by ebachelet** [comment]
I can add this on stage 0, no problem.

assuming the background is written:

- constant : 1 column, b0
- gradient : back = b0 + b1 dback/dX + b2 dback/dY

Agree?

**Comment by rachel3834** [comment]
Markus' post at the top of this thread gives the required column headers.

**Comment by mpgh** [comment]
we have 3 parameter for the gradient, one kernel-intrinic background, background uncertainty, photometric scale factor, photometric scale factor uncertainty and that should do, i.e. 7 parameters.

**Comment by ytsapras** [comment]
If this has been resolved in stage0 we should close the ticket.

**Comment by ebachelet** [comment]
I did not change anything yet to stage0.
