### ISSUE TITLE
Instrument configuration files and Metadata

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#6]
We agreed that we would separate out the instrument-specific configuration parameters from the general pipeline config.json file into inst_config files, and also that there would be a single such file per instrument configuration. These will be stored in .../pyDANDIA/Configs in github as a reference, and customized in the user's ../proc/configs directory in operation.

The instrument config files will need to be identified with the name of the instrument as given in the FITS image header, plus its binning mode since this changes certain necessary parameters.
The files should be named systematically, so that the pipeline can find the right one programmatically. E.g. inst_config_fl03_bin1.json.

When Stage 0 builds the metadata, it will need to
a) read a FITS image header from the dataset and find the camera_id and binning mode
b) use these parameters to figure out which instrument config file to read
c) parse the inst_config file and add the relevant parameters to the metadata.

**Comment by ytsapras** [comment]
Hi all,
I have created instrument configuration files base on the images that we
have downloaded here in HD.
git pull and you can find them in the main Config/ directory.

NOTE: In all instrument config files, I have replaced the "pixeL_scale" key
(which was a string referring to the pixel scale header keyword) with the
 "pix_scale" key, which is the actual value.
"pixeL_scale" still exists untouched in the config.json file, in case
anyone wants to keep using it.

Cheers,
Yiannis

**Comment by ytsapras** [comment]
I have now made sure there are no duplicates in config.json. Please update your repo.

The following (image header-related) keys have been removed from config.json
and can only be found in the individual inst_config_.json files. Note that the
pixeL_scale, giving the header name for the pixel scale is no longer relevant
as it has been replaced by the pix_scale in each inst_config_.json file which
contains the actual value:

datekey
timekey
deckey
rakey
expkey
filtkey
fov
gain
ron
pixeL_scale
imagex1
imagex2
imagey1
imagey2
maxval
minval
obskey
obskeyb
obskeyf
obskeys
oscanx1
oscanx2
oscany1
oscany2

**Comment by ebachelet** [comment]
Stage0 should do this now. I let you close if you are happy with this.

**Comment by ytsapras** [comment]
Hi Etienne,
stage0 breaks when I try to `read_the_inst_config_file` with the following error :

```
In [20]: inst_config = read_the_inst_config_file(setup.pipeline_config_dir, inst_config_file_name, log=log)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-ae55ae6d802a> in <module>()
----> 1 inst_config = read_the_inst_config_file(setup.pipeline_config_dir, inst_config_file_name, log=log)

/home/Tux/ytsapras/Programs/Workspace/pyDANDIA/pyDANDIA/stage0.pyc in read_the_inst_config_file(inst_config_directory, inst_config_file_name, log)
    210     '''
    211 
--> 212     config_file_path = os.path.join(inst_config_directory, inst_config_file_name)
    213 
    214     instrument_configuration = config_utils.read_config(config_file_path)

/home/Tux/ytsapras/Installed_Programs/anaconda/lib/python2.7/posixpath.pyc in join(a, *p)
     66     path = a
     67     for b in p:
---> 68         if b.startswith('/'):
     69             path = b
     70         elif path == '' or path.endswith('/'):

AttributeError: 'NoneType' object has no attribute 'startswith'

```

**Comment by ytsapras** [comment]
Hi Etienne,
Thanks. The HEADERS_SUMMARY table in the metadata file has the column titles incorrectly set. For example, it uses EXPKEY and OBJKEY instead of EXPTIME and OBJECT (the values in the .json files).

In addition, the REDUCTION_PARAMETERS is specific for the instrument - but where do we want to put the filter information for each of the images? At the moment, the metadata only lists the header keyword for the filter (FILTER2). Maybe discuss this with Rachel and make a decision on how we should deal with this. 

My suggestion is that each reduction will be in ONE specific filter, so stage0 would then need to use the filter keyword (in this case, FILTER2) and get the actual value from one of the images from this telescope+camera+filter combination, then set the appropriate column header and put the actual value in the cell.

**Comment by ebachelet** [comment]
Hi

Sure about this? I thought OBJKEY is the name inside the pipeline, and OBJECT is the equivalent for our case, LCO observations, on the header files. 

Regarding the filter, as I said, stage0 try to read from headers everything he got inside reduction_parameters layer. So obviously he find filter for all frames. I am not sure this is a bad thing, it can actually be a good check to do after stage0 finish. Before further processing, does my dataset looks correct? (same filter, same object etc ....)

**Comment by ytsapras** [comment]
I guess it depends on how the pipeline handles the information. For the
i-band filter, for example, the filter key-value pair in the image header
file is FILTER2='ip'. The value ('ip') is not reflected in the metadata
file at the moment but a program can get the filter keyword from the
metadata file and extract the value from the image header.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ebachelet** [comment]
" The value ('ip') is not reflected in the metadata file at the moment"

Not true, it is in headers_summary layer

**Comment by ytsapras** [comment]
This issue is now resolved.
