### ISSUE TITLE
astropy interface

### ISSUE THREAD

**Issue by mpgh** [pyDANDIA/pyDANDIA#60]
ImportError: cannot import name astropy_interface
photometry.py", line 29

**Comment by ebachelet** [comment]
This is a classical problem of codes inside subdirectories. Please cp astropy_interface.py and phot_db.py with all other codes in the main pyDANDIA directory

**Comment by mpgh** [comment]
That partly helps, photometry seems to import photometry and the configs can't be found.

**Comment by rachel3834** [comment]
Can you be more specific Markus?  Looking at photometry.py it doesn't self-import (and python will break if this is true).

**Comment by rachel3834** [comment]
I'm working on an end-to-end test of the pipeline now, and I have integrated phot_db.py and astropy_interface.py with the main pyDANDIA subdirectory.  All future changes to these codes should be made there and not in the db/ subdirectory.  This resolves the import problem.
