### ISSUE TITLE
Foreign Key bug in stage3_db branch

### ISSUE THREAD

**Issue by ebachelet** [pyDANDIA/pyDANDIA#73]
Tried the new branch, found this bug : 

sqlite3.IntegrityError: FOREIGN KEY constraint failed

I fixed some python3 bugs on this branch that I pushed.

**Comment by ytsapras** [comment]
To help with debugging this please save and share here the parameters passed in the last call of phot_db.ingest_astropy_table(conn, 'ref_phot', ref_phot).

**Comment by ytsapras** [comment]
Are we still experiencing this bug? If not, I can close it.

**Comment by rachel3834** [comment]
I think this issue has been dealt with.

**Comment by ytsapras** [comment]
OK, closing.
