### ISSUE TITLE
stage 5 calculation of kernel_size_array can become negative

### ISSUE THREAD

**Issue by rachel3834** [pyDANDIA/pyDANDIA#81]
The calculation of the kernel_size_array entries can go negative in some circumstances, since there is nothing to stop this at lines 93-94 of stage5.py.  

This can cause the stage to crash for some images at line 277, where these parameters are used, when the code encounters -1 for an array index. 

Proposed fix: add a minimum-value limit at line 94, such as:
    for percentile in kernel_percentile:
        kernel_size_tmp = int(4.*float(reduction_metadata.reduction_parameters[1]['KER_RAD'][0]) * np.percentile(fwhms,percentile))
        if kernel_size_tmp % 2 == 0:
            kernel_size_tmp -= 1
            if kernel_size_tmp < 1:
                kernel_size_tmp = 1
        kernel_size_array.append(kernel_size_tmp)

**Comment by mpgh** [comment]
you are right, I have followed your suggestion.
