### ISSUE TITLE
Stage0 resets REDUCTION_STATUS for stage1 to 0 on rerun

### ISSUE THREAD

**Issue by ytsapras** [pyDANDIA/pyDANDIA#9]
When stage0 and stage1 have both finished running and produced the metadata file, if stage0 is run again, it will set on the REDUCTION_STATUS layer stage1 to 0 (from 1) for all images. Do we intend to run stage 0 only once? I assume not, since it will need to record new images, so this should not happen.

**Comment by rachel3834** [comment]
Agreed.  If stage 1 has been run for a given image, then that image's status should be 1.  This should not be reset unless the products of that run are removed or reset, indicating that the stage should be run again.

**Comment by ebachelet** [comment]
This was a function in stage0, as testing purpose, which automatically reset status to 0. We just delete it and we expect normal behaviour.
